language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run demo
  - npm run cypress:run
after_success:
  - npm run semantic-release || true
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
